# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwB8QJZVJLAjfPHLda6JzeyhN3e-1-wP

# **Assignment 1 - Pattern programming in Python**

Name: Mrinmoy M. Dutta

Referral ID: SIRSS2103
"""

number = 5
for i in range(number,0,-1):
  for j in range(0,i):
    print(5, end= " ")
  print()

number = 6
for i in range(number,1,-1):
  for j in range(0,i):
    print(j, end = " ")
  print()

num_1 = 5
num_2 = 1
for i in range(1, num_1 + 1):
  for j in range(0,i):
    print(num_2, end = " ")
  num_2 = num_2 + 2
  print()

number = 5
for i in range(1, number + 1):
  for j in range(i,0,-1):
    print(j,end = " ")
  print()

num_1 = 4
num_2 = 0
for i in range(1, num_1 + 1):
  num_2 = i + num_2
  num_3 = num_2
  for j in range(0, i):
    print(num_3, end = " ")
    num_3 = num_3 - 1
  print()

def series(num_1):
  if num_1 == 0:
    return (1)
  else:
    return (num_1 * series(num_1 - 1))

num_2 = 7
for i in range(0, num_2):
  for j in range(0, i + 1):
    num_3 = int(series(i) / (series(j) * series(i - j)))
    print(num_3, end = " ")
  print()

num_1 = 5
for i in range(1, number + 1):
  for j in range(1, 6):
    num_2 = i if(i > j) else j
    print(num_2, end = " ")
  print()

number = 8
for i in range(1, number + 1):
  for j in range(1, i + 1):
    print(i * j, end = " ")
  print()

value_1 = 6
value_2 = 0
for i in range(value_1, 0, -1):
  for j in range(0, value_2):
    print(" ", end = "")
  for k in range(0, i):
    print("*", end = " ")
  value_2 = value_2 + 1
  print()

value_1 = 7
value_2 = 7
for i in range(1, value_1 + 1):
  for k in range(0, value_2):
    print(" ", end = "")
  for j in range(0, i):
    print("*", end = " ")
  value_2 = value_2 - 1
  print()

value = 6
for i in range(1, value + 1):
  for j in range(0, i):
    print("*", end = " ")
  print()
print()
for k in range(value, 0, -1):
  for l in range(0, k):
    print("*", end = " ")
  print()

value = 5
for i in range(1, value + 1):
  for j in range(0, i):
    print("*", end = " ")
  print()
for k in range(value - 1, 0, -1):
  for l in range(0, k):
    print("*", end = " ")
  print()

num_1 = 5
num_2 = 5
for i in range(1, num_1 + 1):
  for j in range(1, num_2):
    print(" ", end = " ")
  for k in range(0, i):
    print("*", end = " ")
  print()
  num_2 = num_2 - 1
num_2 = 1
for i in range(num_1 - 1, 0, -1):
  for j in range(0, num_2):
    print(" ", end = " ")
  for k in range(0, i):
    print("*", end = " ")
  print()
  num_2 = num_2 + 1

num_1 = 5
num_2 = 0
for i in range(num_1, 0, -1):
  for j in range(0, num_2):
    print(" ", end = "")
  for k in range(0, i):
    print("*", end = " ")
  print()
  num_2 = num_2 + 1
num_2 = 4
for i in range(1, num_1 + 1):
  for j in range(0, num_2):
    print(" ", end = "")
  for k in range(0, i):
    print("*", end = " ")
  print()
  num_2 = num_2 - 1

num_1 = 8
num_2 = 8
for i in range(0, num_1):
  for j in range(0, num_2):
    print("*", end = "")
  for k in range(0, i):
    print("--", end = "")
  for l in range(0, num_2):
    print("*", end = "")
  num_2 = num_2 - 1
  print()